import {
  isBoolean,
  isDateString,
  isEmail,
  isEnum,
  isMobilePhone,
  isNotEmpty,
  isNumber,
  isString,
  isStrongPassword,
  matches,
  maxLength,
  minLength,
  contains,
  equals,
  isArray,
  isBase64,
  isCurrency,
  isCreditCard,
  isDate,
  isDecimal,
  isDefined,
  isIBAN,
  isJWT,
  isInt,
  isURL,
  isUUID,
  isNumberString,
  isNotEmptyObject,
  isIn,
  isNotIn,
} from 'class-validator';

export const requiredConstraintKeys = [isNotEmpty.name];
export const typeConstraintKeys = [
  isString.name,
  isNumber.name,
  isDateString.name,
  isBoolean.name,
  isEnum.name,
];
export const structureConstraintKeys = [
  matches.name,
  isStrongPassword.name,
  minLength.name,
  maxLength.name,
  isEmail.name,
  isMobilePhone.name,
  contains.name,
  equals.name,
  isArray.name,
  isBase64.name,
  isCurrency.name,
  isCreditCard.name,
  isDate.name,
  isDecimal.name,
  isDefined.name,
  isIBAN.name,
  isJWT.name,
  isInt.name,
  isURL.name,
  isUUID.name,
  isNumberString.name,
  isNotEmptyObject.name,
  isIn.name,
  isNotIn.name,
];
