'use client'

import { Button } from '@/components/globalComponents'
import React, { MouseEventHandler } from 'react'
// import { QRCodeSVG } from 'qrcode.react';
import Image from 'next/image';
import { EnableTwoFactorAuthProps } from '@/types/webappTypes/appTypes';
import { InputElement } from '@/components/forms';

const EnableTwoFactorAuth = ({
  close,
  next,
  qrcode_key,
  qrcode_image,
  setCode,
  loading
}: EnableTwoFactorAuthProps) => {
  const handleEnable = () => {
    next();
  }

  const handleCode = (value: string) => {
    if (value?.length <= 6 ) {
      setCode(value?.toString()?.replace(/[^0-9.]/g, ''));
    }
  }

  return (
    <section className='w-full flex gap-[25px] flex-col'>
      <ul className='w-full px-[20px] flex list-decimal flex-col gap-[12px]'>
        <li className='text-o-text-medium text-f14'>
          To enable 2FA, you need to install an authenticator 
          app like Authy, or Google Authenticator.
        </li>

        <li className='w-full'>
          <div className='flex flex-col gap-[12px] text-o-text-medium text-f14 w-full'>
            Scan the QR Code below with your authenticator app.

            <div className='w-full flex justify-center'>
              {/* <QRCodeSVG value={qrcode_key} /> */}
              <Image 
                src={qrcode_image}
                alt='QRCODE'
                height={166}
                width={166}
              /> 
            </div>
            
            <div className='w-full flex flex-col gap-[12px]'>
              <div className='w-full text-center'>
                Alternatively, you can use the QR Code Key:&#160;
                <span className='text-f14 font-[600] text-o-text-dark'>
                  {qrcode_key}
                </span>
              </div>
            </div>
          </div>
        </li>

        <li className='text-o-text-medium text-f14'>
          <div className='w-full flex flex-col gap-[5px]'>
            Enter the TOTP generated by the app and click enable.
            <InputElement 
              name='code'
              type='text'
              placeholder='6-digit code'
              // value={code}
              changeValue={(value: string) => handleCode(value)}
              required
            />
          </div>
        </li>
      </ul>

      <div className='w-full flex justify-between items-center gap-5'>
        <Button 
          title='Cancel'
          effect={close}
          outlined
        />

        <Button 
          title='Enable'
          loading={loading}
          containerStyle='!w-[86px]'
          effect={handleEnable}
        />
      </div>
    </section>
  )
}

export default EnableTwoFactorAuth