'use client'

import { Button } from '@/components/globalComponents'
import React, { MouseEventHandler } from 'react'
import { QRCodeSVG } from 'qrcode.react';

const EnableTwoFactorAuth = ({
  close,
  next,
  qrcode_key
}: { 
  close: MouseEventHandler<HTMLButtonElement>,
  next: () => void,
  qrcode_key: string
}) => {
  const handleEnable = () => {
    next();
  }

  return (
    <section className='w-full flex gap-[32px] flex-col'>
      <ul className='w-full px-[20px] flex list-decimal flex-col gap-[16px]'>
        <li className='text-o-text-medium text-f14'>
          To enable 2FA, you need to install an authenticator 
          app like Authy, or Google Authenticator.
        </li>

        <li className='w-full flex flex-col gap-[16px] text-o-text-medium text-f14'>
          Scan the QR Code below with your authenticator app.

          <div className='w-full flex justify-center'>
            <QRCodeSVG value={qrcode_key} />
          </div>
          
          <div className='w-full flex flex-col gap-[16px]'>
            <div className='w-full text-center'>
              Alternatively, you can use the QR Code Key:&#160;
              <span className='text-f14 font-[600] text-o-text-dark'>
                {qrcode_key}
              </span>
            </div>
          </div>
        </li>

        <li className='text-o-text-medium text-f14'>
          Enter the TOTP generated by the app and click enable.
        </li>
      </ul>

      <div className='w-full flex justify-between items-center gap-5'>
        <Button 
          title='Cancel'
          effect={close}
          outlined
        />

        <Button 
          title='Enable'
          containerStyle='!w-[86px]'
          effect={handleEnable}
        />
      </div>
    </section>
  )
}

export default EnableTwoFactorAuth